import { playwright } from "@vitest/browser-playwright";
import { visualizer } from "rollup-plugin-visualizer";
import { defineConfig, loadEnv } from "vite";
import { imagetools } from "vite-imagetools";
import { ViteImageOptimizer } from "vite-plugin-image-optimizer";

export default defineConfig(({ mode }) => {
	loadEnv(mode, ".", "");
	return {
		base: process.env.NODE_ENV === "production" ? "/legacys-end/" : "/",
		server: {
			port: 3000,
			host: "0.0.0.0",
		},
		define: {
			"process.env.NODE_ENV": JSON.stringify(
				mode === "test" ? "production" : process.env.NODE_ENV,
			),
		},
		resolve: {
			alias: {
				"node:module": new URL("./src/setup/empty-module.js", import.meta.url)
					.pathname,
			},
		},
		plugins: [
			ViteImageOptimizer({
				includePublic: true,
				exclude: /\.webp$/, // Don't re-process webp generated by imagetools
				png: { quality: 80 },
				jpeg: { quality: 80 },
				svg: {
					plugins: [
						{ name: "removeViewBox", active: false },
						{ name: "sortAttrs", active: true },
					],
				},
			}),
			imagetools(),
			process.env.ANALYZE === "true" &&
				visualizer({
					filename: "stats.html",
					open: true,
					gzipSize: true,
					brotliSize: true,
				}),
		],
		optimizeDeps: {
			include: ["@awesome.me/webawesome/dist/components/spinner/spinner.js"],
			esbuildOptions: {
				target: "esnext",
			},
		},
		test: {
			silent: true,
			browser: {
				enabled: true,
				headless: true,
				provider: playwright(),
				instances: [{ browser: "chromium" }],
			},
			env: {
				NODE_ENV: "production",
			},
			coverage: {
				provider: "v8",
				reporter: ["text", "json", "html", "json-summary"],
				include: ["src/**/*.js"],
				exclude: [
					// Test files
					"**/*.test.js",
					"**/__tests__/**",

					// Generated files
					"src/generated/**",

					// Data-only files (no logic to test)
					"src/content/**",
					"src/constants/**",
					"src/contexts/**",
					"src/styles/**",

					// Setup/initialization code (hard to test in isolation)
					"src/setup/**",
				],
			},
		},
	};
});
