import minifyHTML from "@lit-labs/rollup-plugin-minify-html-literals";
import { playwright } from "@vitest/browser-playwright";
import { visualizer } from "rollup-plugin-visualizer";
import { defineConfig, loadEnv } from "vite";
import { imagetools } from "vite-imagetools";
import babel from "vite-plugin-babel";
import { ViteImageOptimizer } from "vite-plugin-image-optimizer";
import { VitePWA } from "vite-plugin-pwa";

const playgroundDevServerPlugin = () => ({
	name: "playground-dev-server",
	configureServer(server) {
		server.middlewares.use((req, res, next) => {
			if (req.url) {
				const pathname = req.url.split("?")[0];
				if (pathname.startsWith("/session-")) {
					res.statusCode = 404;
					res.end("Playground session file not found on server.");
					return;
				}
			}
			next();
		});
	},
});

export default defineConfig(({ mode }) => {
	loadEnv(mode, ".", "");
	return {
		base: process.env.NODE_ENV === "production" ? "/legacys-end/" : "/",
		server: {
			port: 3000,
			host: "0.0.0.0",
		},
		define: {
			"process.env.NODE_ENV": JSON.stringify(
				mode === "test" ? "production" : process.env.NODE_ENV,
			),
		},
		resolve: {
			alias: {
				"node:module": new URL("./src/setup/empty-module.js", import.meta.url)
					.pathname,
			},
		},
		plugins: [
			playgroundDevServerPlugin(),
			minifyHTML({
				exclude: ["node_modules/**"],
			}),
			ViteImageOptimizer({
				includePublic: true,
				exclude: /\.webp$/, // Don't re-process webp generated by imagetools
				png: { quality: 80 },
				jpeg: { quality: 80 },
				svg: {
					plugins: [
						{ name: "removeViewBox", active: false },
						{ name: "sortAttrs", active: true },
					],
				},
			}),
			imagetools(),
			babel({
				babelConfig: {
					babelrc: false,
					configFile: false,
					plugins: [
						["@babel/plugin-proposal-decorators", { version: "2023-05" }],
					],
				},
			}),
			process.env.ANALYZE === "true" &&
				visualizer({
					filename: "stats.html",
					open: true,
					gzipSize: true,
					brotliSize: true,
				}),
			VitePWA({
				registerType: "autoUpdate",
				includeAssets: [
					"favicon.ico",
					"apple-touch-icon.png",
					"assets/**/*.png",
					"assets/**/*.jpg",
					"assets/**/*.mp3",
				],
				workbox: {
					globPatterns: ["**/*.{js,css,html,ico,png,svg,webp,jpg,mp3}"],
					// Do not cache the playground service worker generated files
					navigateFallbackDenylist: [/^\/__playground_swfs_/],
					maximumFileSizeToCacheInBytes: 5000000,
				},
				manifest: {
					name: "Legacy's End",
					short_name: "Legacy's End",
					description: "A programming puzzle game",
					theme_color: "#0f172a",
					background_color: "#0f172a",
					display: "standalone",
					orientation: "portrait",
					icons: [
						{
							src: "icons/pwa-192x192.png",
							sizes: "192x192",
							type: "image/png",
						},
						{
							src: "icons/pwa-512x512.png",
							sizes: "512x512",
							type: "image/png",
						},
					],
				},
			}),
		],
		build: {
			target: "es2022",
			rollupOptions: {
				input: {
					main: "index.html",
					history: "history.html",
				},
			},
		},
		optimizeDeps: {
			exclude: ["playground-elements"],
			include: ["@awesome.me/webawesome/dist/components/spinner/spinner.js"],
			esbuildOptions: {
				target: "es2022",
			},
		},
		test: {
			exclude: [
				"**/e2e/**",
				"**/node_modules/**",
				"**/dist/**",
				"**/tooling/**",
			],
			silent: false,
			browser: {
				enabled: true,
				headless: true,
				provider: playwright(),
				instances: [{ browser: "chromium" }],
			},
			env: {
				NODE_ENV: "production",
			},
			coverage: {
				provider: "v8",
				reporter: ["text", "json", "html", "json-summary"],
				include: ["src/**/*.js"],
				exclude: [
					// Test files
					"**/*.test.js",
					"**/__tests__/**",

					// Generated files
					"src/generated/**",

					// Data-only files (no logic to test)
					"src/content/**",
					"src/constants/**",
					"src/contexts/**",
					"src/styles/**",

					// Setup/initialization code (hard to test in isolation)
					"src/setup/**",
				],
				thresholds: {
					statements: 64,
					branches: 45,
					functions: 50,
					lines: 66,
				},
			},
		},
	};
});
