name: "🐛 Bug Report"
description: "Report something that is broken"
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "What happened?"
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: "Steps to Reproduce"
      description: "How can we see the bug?"
  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "What should have happened?"
